Django/semi_restful_project/apps/semi_restful/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new$', views.new, name='new'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    url(r'^edit/(?P<id>\d+)$', views.edit, name='edit'),
    url(r'^create$', views.create, name='create'),
    url(r'^destroy/(?P<id>\d+)$', views.destroy, name='destroy'),
    url(r'^update/(?P<id>\d+)$', views.update, name='update')
]

Django/semi_restful_project/semi_restful_project/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^products/', include('apps.semi_restful.urls', namespace='products')),
]

Django/semi_restful_project/apps/semi_restful/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/semi_restful_project/apps/semi_restful/views.py
from django.shortcuts import render, redirect
from .models import Product
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    context = {
                'products': Product.objects.all()
                }
    return render(request, 'semi_restful/index.html', context)

def new(request):
    return render(request, 'semi_restful/new.html')

def create(request):
    Product.objects.create(name=request.POST['name'], description=request.POST['description'], price=request.POST['price'])
    return redirect(reverse('products:index'))

def destroy(request, id):
    Product.objects.get(id=id).delete()
    return redirect(reverse('products:index'))

def show(request, id):
    context = {
                'product': Product.objects.get(id=id)
                }
    return render(request, 'semi_restful/show.html', context)

def edit(request, id):
    context = {
                'product': Product.objects.get(id=id)
                }
    return render(request, 'semi_restful/edit.html', context)

def update(request, id):
    to_update = Product.objects.get(id=id)
    to_update.name = request.POST['name']
    to_update.description = request.POST['description']
    to_update.price = request.POST['price']
    to_update.save()
    return redirect(reverse('products:index'))

Django/semi_restful_project/apps/semi_restful/templates/semi_restful/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Edit Product {{product.id}} | Semi Restful Route Demo</title>
  </head>
  <body>
    <h1>Edit Product {{product.id}}</h1>
    <form action="{% url 'products:update' id=product.id %}" method='post'>
      {% csrf_token %}
      <label>Name</label>
      <input type='text' onFocus="this.value='{{product.name}}'" name='name'>
      <label>Description</label>
      <input type='text' onFocus="this.value='{{product.description}}'" name='description'>
      <label>Price</label>
      <input type='text' onFocus="this.value='{{product.price}}'" name='price'>
      <input type='submit' value='Update'>
    </form>
    <p>
      <a href="{% url 'products:show' id=product.id %}">Show</a> |
      <a href="{% url 'products:index' %}">Home</a>
    </p>
  </body>
</html>

Django/semi_restful_project/apps/semi_restful/templates/semi_restful/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>All Products | Semi Restful Route Demo</title>
  </head>
  <body>
    <h1>Products</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products %}
          <tr>
            <td>{{product.name}}</td>
            <td>{{product.description}}</td>
            <td>${{product.price}}</td>
            <td><a href="{% url 'products:show' id=product.id %}">Show</a> <span class='barriers'>|</span> <a href="{% url 'products:edit' id=product.id %}">Edit</a> <span class='barriers'>|</span> <form action="{% url 'products:destroy' id=product.id %}" method='post'>{% csrf_token %}<input type='submit' value='Remove'></form></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'products:new' %}">Add a new product</a>
  </body>
</html>

Django/semi_restful_project/apps/semi_restful/templates/semi_restful/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create a new product | Semi Restful Route Demo</title>
  </head>
  <body>
    <h1>Add a new product</h1>
    <form action="{% url 'products:create' %}" method='post'>
    {% csrf_token %}
      <label>Name</label>
      <input type='text' name='name'>
      <label>Description</label>
      <input type='text' name='description'>
      <label>Price</label>
      <input type='text' name='price'>
      <input type='submit' value='Create'>
    </form>
    <a href="{% url 'products:index' %}">Go back</a>
  </body>
</html>

Django/semi_restful_project/apps/semi_restful/templates/semi_restful/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Product {{product.id}} Info | Semi Restful Route Demo</title>
    <style type='text/css'>
      #labels{
        display: inline-block;
      }
      #labels label{
        display: block;
        line-height: 200%;
        font-weight: bold;
      }
      #values{
        display: inline-block;
        margin-left: 10px;
        line-height: 100%;
      }
    </style>
  </head>
  <body>
    <h1>Product {{product.id}}</h1>
    <div id='labels'>
      <label>Name:</label>
      <label>Description:</label>
      <label>Price:</label>
    </div>
    <div id='values'>
      <p>{{product.name}}</p>
      <p>{{product.description}}</p>
      <p>${{product.price}}</p>
    </div>
    <p>
      <a href="{% url 'products:edit' id=product.id %}">Edit</a> |
      <a href="{% url 'products:index' %}">Back</a>
    </p>
  </body>
</html>